#!/bin/sh

command="$1"

# Help text to be displayed
helpFunc()
{
printf "Commands: \n
g - start emacs in gui mode
t - start emacs in terminal mode
sr - restarts systemd emacs daemon.
ds - doom sync."
}


clientActive=$(pgrep -f "emacs --daemon")


if [ -z "$1" ]
 then
     emacsclient -nc
fi

startDaemon()
{
emacs --daemon > /dev/null
}


killDaemon()
{
pkill -f "emacs --daemon" > /dev/null # This will silence output
}



case "$command" in
     -sr) killDaemon # Will kill and then restart the emacs daemon.
          startDaemon ;;

     -ds) doom sync ;; # Uses doom sync to sync up packages and configuration files.

     -g)  emacsclient -nc ;; # This will start the gui emacsclient

     -t) # This will start the terminal client
          # TODO Have to change this to detect emacs on processes instead
          if [ -z "$clientActive" ]; then
                startDaemon
                emacsclient -nw
          else
               emacsclient -tty
          fi    ;;
    -h) helpfunc ;;
    # TODO Have to make this so that when no argument is passed it will not print the help function.
    #*) helpFunc ;;

esac


